#!/bin/bash

set -v
set -e

SPACENET=$1
OUTPUT=$2

mkdir -p $OUTPUT/labels/grayscale
mkdir -p $OUTPUT/labels/color

find $SPACENET -name *Public_*.geojson | \
  parallel "./rasterize {} $SPACENET/processedData/3band/3band_ $OUTPUT" \
  > $OUTPUT/all.txt

ls $OUTPUT/labels/grayscale | parallel "./label_counts $OUTPUT/labels/grayscale/{}" \
  > $OUTPUT/labels/label-counts.txt

./label_stats $OUTPUT/labels/label-counts.txt > $OUTPUT/labels/label-stats.csv

cp classes.json $OUTPUT/

split -l $[ $(wc -l $OUTPUT/all.txt|cut -d" " -f1) * 70 / 100 ] -a1 \
  $OUTPUT/all.txt $OUTPUT/split
cp $OUTPUT/splita $OUTPUT/train.txt
cp $OUTPUT/splitb $OUTPUT/val.txt
